"""empty message

Revision ID: 198df351a902
Revises: 0b8cb48ded18
Create Date: 2018-03-14 10:15:47.358038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '198df351a902'
down_revision = '0b8cb48ded18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hebschools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hebschools')
    # ### end Alembic commands ###
