"""empty message

Revision ID: 32c814bb15f8
Revises: a47ccc048927
Create Date: 2018-03-20 10:22:54.623561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32c814bb15f8'
down_revision = 'a47ccc048927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthdayDD', sa.Text(), nullable=True))
    op.add_column('students', sa.Column('bmDD', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'bmDD')
    op.drop_column('students', 'birthdayDD')
    # ### end Alembic commands ###
