"""empty message

Revision ID: 53ea55081b52
Revises: 32c814bb15f8
Create Date: 2018-03-20 12:21:06.518637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ea55081b52'
down_revision = '32c814bb15f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('over200', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'over200')
    # ### end Alembic commands ###
