"""empty message

Revision ID: a47ccc048927
Revises: 
Create Date: 2018-03-19 23:23:55.111982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a47ccc048927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hebschools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('childName', sa.String(), nullable=True),
    sa.Column('ranking_main', sa.Integer(), nullable=True),
    sa.Column('ranking_familyMinyan', sa.Integer(), nullable=True),
    sa.Column('ranking_torahInTheRound', sa.Integer(), nullable=True),
    sa.Column('atVenue', sa.Boolean(), nullable=True),
    sa.Column('accommodation_other', sa.Text(), nullable=True),
    sa.Column('twin', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('hebSchool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hebSchool_id'], ['hebschools.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nondates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('greg', sa.Date(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nondates')
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('hebschools')
    # ### end Alembic commands ###
