"""empty message

Revision ID: dbdd1ecba7a3
Revises: 
Create Date: 2018-03-19 15:49:56.560618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdd1ecba7a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hebschools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('childName', sa.String(), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=True),
    sa.Column('ranking_main', sa.Integer(), nullable=True),
    sa.Column('ranking_familyMinyan', sa.Integer(), nullable=True),
    sa.Column('ranking_torahInTheRound', sa.Integer(), nullable=True),
    sa.Column('atVenue', sa.Boolean(), nullable=True),
    sa.Column('accommodation', sa.Text(), nullable=True),
    sa.Column('twin', sa.Boolean(), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('hebSchool_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hebSchool_id'], ['hebschools.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('email', 'childName'),
    sa.UniqueConstraint('id')
    )
    op.create_table('non_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('non_dates')
    op.drop_table('students')
    op.drop_table('schools')
    op.drop_table('hebschools')
    # ### end Alembic commands ###
